const DISPENSATION = "DISPENSATIONOOOOOOOOOOOOOOOOOOOOOOOOOO";
const INVENTORY = "INVENTORYOOOOOOOOOOOOOOOOOOOOOOOOOOOOO";
const INVENTORY_ADJUSTMENT_POSITIVE = "INVENTORYADJUSTPOSITIVEOOOOOOOOOOOOOOO";
const INVENTORY_ADJUSTMENT_NEGATIVE = "INVENTORYADJUSTNEGATIVEOOOOOOOOOOOOOOO";
const RECEPTION = "RECEPTIONOOOOOOOOOOOOOOOOOOOOOOOOOOOOO";
const RECEPTION_RETURN = "RECEPTIONRETURNOOOOOOOOOOOOOOOOOOOOOOO";
const PRODUCT_RETURN = "PRODUCTRETURNOOOOOOOOOOOOOOOOOOOOOOOOO";
const DONATION = "DONATIONENTRYOOOOOOOOOOOOOOOOOOOOOOOOO";
const TRANSFER_IN = "TRANSFERINOOOOOOOOOOOOOOOOOOOOOOOOOOOO";
const TRANSFER_OUT = "TRANSFEROUTOOOOOOOOOOOOOOOOOOOOOOOOOOO";
const EXPIRY = "EXPIRYOUTOOOOOOOOOOOOOOOOOOOOOOOOOOOOO";
const THIEF = "THIEFOUTOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO";
const DESTROYED = "DESTROYEDOUTOOOOOOOOOOOOOOOOOOOOOOOOOO";
const SPOILED = "SPOILEDOUTOOOOOOOOOOOOOOOOOOOOOOOOOOOO";
const OTHER_OUT = "OTHEROUTOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO";
const DISTRIBUTION = "DISTRIBUTIONOOOOOOOOOOOOOOOOOOOOOOOOOO";
const URGENT_REPORT = "URGENTREPORTOOOOOOOOOOOOOOOOOOOOOOOOOO";
const REPORT = "REPORTOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO";

export const OperationType = {
    DISPENSATION,
    INVENTORY,
    RECEPTION,
    TRANSFER_IN,
    TRANSFER_OUT,
    INVENTORY_ADJUSTMENT_POSITIVE,
    INVENTORY_ADJUSTMENT_NEGATIVE,
    RECEPTION_RETURN,
    PRODUCT_RETURN,
    DONATION,
    EXPIRY,
    THIEF,
    DESTROYED,
    SPOILED,
    OTHER_OUT,
    DISTRIBUTION,
    REPORT,
    URGENT_REPORT,
};

const DIRECT_CLIENT = "NPSPCLIENTCCCCCCCCCCCCCCCCCCCCCCCCCC";
const LOCATION_PROGRAMS = "AVAILPRGRMCCCCCCCCCCCCCCCCCCCCCCCCCC";
const LOCATION_CODE = "ccb5b9f5-9432-485b-973b-6cde77f4ea3d";
export const LocationAttributeType = {
    DIRECT_CLIENT,
    LOCATION_PROGRAMS,
    LOCATION_CODE,
};

const INVENTORY_TYPE = "INVENTORYTYPEAAAAAAAAAAAAAAAAAAAAAAAAA";
const ENCOUNTER = "ENCOUNTERAAAAAAAAAAAAAAAAAAAAAAAAAAA";
const DISPENSATION_END_DATE = "TREATMENTENDDATEAAAAAAAAAAAAAAAAAAAAAA";
const DISPENSATION_DURATION = "TREATMENTDURATIONAAAAAAAAAAAAAAAAAAAAA";
const DISPENSATION_PROVIDER = "PROVIDERAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
const DISPENSATION_PRESCRIPTION_DATE = "PRESCRIPTIONDATEAAAAAAAAAAAAAAAAAAAA";
const DISPENSATION_GOAL = "GOALAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
const DISPENSATION_REGIME = "REGIMENAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
const DISPENSATION_REGIME_LINE = "REGIMENLINEAAAAAAAAAAAAAAAAAAAAAAAAAAA";
const PATIENT_AGE = "PATIENTAGEAAAAAAAAAAAAAAAAAAAAAAAAAA";
const PATIENT_GENDER = "PATIENTGENDERAAAAAAAAAAAAAAAAAAAAAAA";
const PATIENT = "PATIENTAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

export const OperationAttributeType = {
    INVENTORY_TYPE,
    ENCOUNTER,
    DISPENSATION_END_DATE,
    DISPENSATION_DURATION,
    DISPENSATION_PROVIDER,
    DISPENSATION_GOAL,
    DISPENSATION_REGIME,
    DISPENSATION_REGIME_LINE,
    PATIENT_AGE,
    PATIENT_GENDER,
    PATIENT,
    DISPENSATION_PRESCRIPTION_DATE
};

const PROVIDER_LOCATION = "LOCATIONPPPPPPPPPPPPPPPPPPPPPPPPPPPP";

export const ProviderAttributeType = {
    PROVIDER_LOCATION,
};
