export enum Incidence {
  NEGATIVE = "NEGATIVE",
  POSITIVE = "POSITIVE",
  EQUAL = "EQUAL",
  NONE = "NONE",
}

export enum OperationStatus {
  AWAITING_VALIDATION = "AWAITING_VALIDATION",
  DISABLED = "DISABLED",
  CANCELED = "CANCELED",
  VALIDATED = "VALIDATED",
  NOT_COMPLETED = "NOT_COMPLETED",
  SUBMITTED = "SUBMITTED",
  AWAITING_TREATMENT = "AWAITING_TREATMENT",
  TREATED = "TREATED",
}

export enum QuantityType {
  DISPENSATION = "DISPENSATION",
  PACKAGING = "PACKAGING",
}
